CREATE TABLE IF NOT EXISTS `admin_galleries` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(500) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `admin_gallery_images` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `gallery_id` INT NOT NULL,
  `title` VARCHAR(500) DEFAULT '',
  `image_path` VARCHAR(1000) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
